# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy files
COPY pyproject.toml ./
COPY requirements.txt ./
COPY src ./src
COPY sketchup.json ./
COPY su_mcp.rb ./
COPY LICENSE ./
COPY README.md ./

# Install build dependencies
RUN pip install --upgrade pip

# Install the project
RUN pip install .

# Expose default Sketchup port (if applicable)
EXPOSE 9876

# Command to run the MCP server
CMD ["sketchup-mcp"]
